---
editor: 
  markdown: 
    wrap: 72
---

**STAT 306 Interim Proposal**

Group Members:

A\) Data Source and Collection

We will use the Life Expectancy (WHO) dataset from Kaggle. This dataset
was compiled from the World Health Organization (WHO) Global Health
Observatory data repository and United Nations economic data covering
the years 2000–2015 for 193 countries. It contains health, demographic,
socioeconomic, and immunization indicators related to life expectancy.
Data were merged into one dataset with 22 columns and 2938 observations.

B\) Variable Description

| variable name                   | variable type | description                                                                                            |
|------------------------------|-------------------|-----------------------|
| Country                         | categorical   | Name of the country                                                                                    |
| Year                            | numerical     | Year of observation                                                                                    |
| Status                          | categorical   | The status of country (Developing or Developed)                                                        |
| Life expectancy                 | numberic      | Life Expectancy in age                                                                                 |
| Adult Mortality                 | numberic      | Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population) |
| infant deaths                   | numberic      | Number of Infant Deaths per 1000 population                                                            |
| Alcohol                         | numberic      | Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol)                             |
| percentage expenditure          | numberic      | Expenditure on health as a percentage of Gross Domestic Product per capita(%)                          |
| Hepatitis B                     | numberic      | Hepatitis B (HepB) immunization coverage among 1-year-olds (%)                                         |
| Measles                         | numberic      | number of reported cases per 1000 population                                                           |
| BMI                             | numberic      | Average Body Mass Index of entire population                                                           |
| under-five deaths               | numberic      | Number of under-five deaths per 1000 population                                                        |
| Polio                           | numberic      | Polio (Pol3) immunization coverage among 1-year-olds (%)                                               |
| Total expenditure               | numberic      | General government expenditure on health as a percentage of total government expenditure (%)           |
| Diphtheria                      | numberic      | Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%)             |
| HIV/AIDS                        | numberic      | Deaths per 1 000 live births HIV/AIDS (0-4 years)                                                      |
| GDP                             | numberic      | Gross Domestic Product per capita (in USD)                                                             |
| Population                      | numberic      | Population of the country                                                                              |
| thinness 1-19 years             | numberic      | Prevalence of thinness among children and adolescents for Age 10 to 19 (%)                             |
| thinness 5-9 years              | numberic      | Prevalence of thinness among children for Age 5 to 9(%)                                                |
| Income composition of resources | numberic      | Human Development Index in terms of income composition of resources (index ranging from 0 to 1)        |
| Schooling                       | numberic      | Number of years of Schooling(years)                                                                    |

C\) Research Question and Context

D\) Group Roles and Responsibilities

Name (student num): Data preparation and organization

Member 2: Exploratory data analysis and visualization

Member 3: Regression modelling and diagnostic checks

Member 4: Model selection, interpretation, and report writing

All four members are expected to contribute to the interpretation and
revision of the final report, and responsibilities will be shared
equally.
